### ISSUE TITLE
An error occurred loading file: package:mailer2/mailer.dart

### ISSUE THREAD

**Issue by suesslin** [tomyeh/mailer#1]
Why does it keep telling me I apparently haven't got it installed... 

```Dart
dependencies:
  mailer2:
```

I added this to my pubspec.yaml file, and ran pub get. Then I followed what the walkthrough said and accordingly set up everything. (I know this is kind of useless if the package can't be found).

But why is this?

**Comment by tomyeh** [comment]
Strange! It works fine here. Is there any conflict among the packages you installed?

**Comment by suesslin** [comment]
No! I have just executed it as is. I used stagehand for the project creation (web-simple)

**Comment by butlermatt** [comment]
FYI, based on the package name, it looks like you should be using `import "package:mailer/mailer.dart";` because while the package name is mailer2 on pub the package name in pubspec says mailer.
