### ISSUE TITLE
Error when running demo 

### ISSUE THREAD

**Issue by hiadamk** [tomyeh/mailer#2]
Error occurred: type '_AsBroadcastStream<dynamic>' is not a subtype of type 'Stream<Envelope>' where
  _AsBroadcastStream is from dart:async
  Stream is from dart:async
  Envelope is from package:mailer2/mailer.dart

This is all that is printed in my console.
I try to send the email to my personal email address and as the username and password use the same email address but without the @gmail.com and my standard password.
I upgraded my flutter to the latest version yesterday and flutter doctor runs smoothly with no errors

**Comment by tomyeh** [comment]
It shall be fixed in 1.2.0+1. If not, please reopen it.
