### ISSUE TITLE
Put Image from device to HTML

### ISSUE THREAD

**Issue by kartzhai** [tomyeh/mailer#4]
hi,

i like to put an image from device and put it on html. image file already on the function.
what i know to load an image on html is using this example <img src="/images/html5.gif" alt="HTML5 Icon" style="width:128px;height:128px;">.

in src what string i should write? since the image file on function i i have no idea to put the string

**Comment by tomyeh** [comment]
It is an email, so it must be a valid URL. That is, you have to put the image to somewhere any one can access via HTTP.
