### ISSUE TITLE
Null Safety

### ISSUE THREAD

**Issue by rlbartz** [tomyeh/mailer#6]
I am currently using this fork because of ReplyTo feature. But after migrating my app to null safety I could not use it anymore. Is there a plan to update this fork to null safety?

**Comment by tomyeh** [comment]
No, I plan to drop this fork and use [kaisellgren/mailer](https://github.com/kaisellgren/mailer) directly.

Please specify the Reply-To header directly if you have to.

**Comment by professorbartz** [comment]
I made some test, and specifying Reply-To header was definitely the solution. I just jumped to kaisellgren/mailer.
Thank you so much.

**Comment by rlbartz** [comment]
I made some test, and specifying Reply-To header was definitely the solution. I just jumped to kaisellgren/mailer.
Thank you so much.
